version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:25.2.0
    steps:
      - checkout
      - run:
          command: "npm install && npm test"

workflows:
  test-workflow:
    jobs:
      - test
